twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/src/Shared/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        '%kernel.project_dir%/src/Shared/templates': Shared
        '%kernel.project_dir%/src/Page/templates': Page
        '%kernel.project_dir%/src/Module/Sponsor/templates': Sponsor
        '%kernel.project_dir%/src/Module/Team/templates': Team

when@test:
    twig:
        strict_variables: true
